libSGP: SGP_SuccessiveConvolutions.c File Reference
SGP_SuccessiveConvolutions.c File Reference
#include "SGP_SuccessiveConvolutions.h"
#include "SGP_Constants.h"
#include "SGP_Utils.h"
#include "SGP_RDD.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>
#include <malloc.h>
Data Structures
struct aKList
Defines
#define MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT 0.002
#define DEBUG_INTERVALS 8
#define DEBUG_MEAN 10.0f
#define DEBUG_SIGMA 1.0f
Functions
void SGP_SC_get_f1_array_size (long *n, float *E_MeV_u, long *particle_no, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, long *N2, long *n_bins_f1, float *f1_parameters)
void SGP_SC_get_f1 (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, long *N2, long *n_bins_f1, float *f1_parameters, float *norm_fluence, float *dose_contribution_Gy, float *f_parameters, float *f1_d_Gy, float *f1_dd_Gy, float *f1)
void SGP_SC_get_f_array_size (float *u, float *fluence_factor, long *N2, long *n_bins_f1, float *f1_d_Gy, float *f1_dd_Gy, float *f1, long *n_bins_f, float *u_start, long *n_convolutions)
void SGP_SC_get_f_start (float *u_start, long *n_bins_f1, long *N2, float *f1_d_Gy, float *f1_dd_Gy, float *f1, long *n_bins_f, float *f_d_Gy, float *f_dd_Gy, float *f_start)
aKList SGP_SC_NORMAL (aKList theKList)
aKList SGP_SC_OUTPUT (aKList theKList)
aKList SGP_SC_INTERP (aKList theKList)
aKList SGP_SC_RESET (aKList theKList)
aKList SGP_SC_ZERO (aKList theKList)
aKList SGP_SC_SHRINK (aKList theKList)
aKList SGP_SC_FOLD (aKList theKList)
void SGP_SuccessiveConvolutions (float *u, long *n_bins_f, long *N2, long *n_bins_f_used, float *f_d_Gy, float *f_dd_Gy, float *f, float *f0, float *fdd, float *dfdd, float *d, bool *write_output, bool *shrink_tails, float *shrink_tails_under, bool *adjust_N2)
Define Documentation
#define DEBUG_INTERVALS 8
Definition at line 21 of file SGP_SuccessiveConvolutions.c.
#define DEBUG_MEAN 10.0f
Definition at line 22 of file SGP_SuccessiveConvolutions.c.
#define DEBUG_SIGMA 1.0f
Definition at line 23 of file SGP_SuccessiveConvolutions.c.
#define MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT 0.002
Definition at line 20 of file SGP_SuccessiveConvolutions.c.
Function Documentation
aKList SGP_SC_FOLD (aKList theKList)
Definition at line 975 of file SGP_SuccessiveConvolutions.c.
References aKList::A, aKList::adjust_N2, aKList::array_size, aKList::BI, aKList::CN, aKList::DE, aKList::DI, aKList::F, aKList::F0, aKList::H, aKList::H0, aKList::LEF, aKList::LEH, aKList::MIE, aKList::MIF, aKList::MIH, aKList::N2, SGP_SC_INTERP(), SGP_SC_RESET(), SGP_SC_ZERO(), and aKList::X.
void SGP_SC_get_f1 (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, long * N2, long * n_bins_f1, float * f1_parameters, float * norm_fluence, float * dose_contribution_Gy, float * f_parameters, float * f1_d_Gy, float * f1_dd_Gy, float * f1)
Definition at line 112 of file SGP_SuccessiveConvolutions.c.
References FMAX, FMIN, LMAX, locate(), MeV_g_to_J_kg, and SGP_r_RDD_m().
void SGP_SC_get_f1_array_size (long * n, float * E_MeV_u, long * particle_no, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, long * N2, long * n_bins_f1, float * f1_parameters)
Definition at line 26 of file SGP_SuccessiveConvolutions.c.
References FMAX, FMIN, and SGP_RDD_f1_parameters().
void SGP_SC_get_f_array_size (float * u, float * fluence_factor, long * N2, long * n_bins_f1, float * f1_d_Gy, float * f1_dd_Gy, float * f1, long * n_bins_f, float * u_start, long * n_convolutions)
Definition at line 404 of file SGP_SuccessiveConvolutions.c.
References MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT.
void SGP_SC_get_f_start (float * u_start, long * n_bins_f1, long * N2, float * f1_d_Gy, float * f1_dd_Gy, float * f1, long * n_bins_f, float * f_d_Gy, float * f_dd_Gy, float * f_start)
Definition at line 476 of file SGP_SuccessiveConvolutions.c.
aKList SGP_SC_INTERP (aKList theKList)
Definition at line 744 of file SGP_SuccessiveConvolutions.c.
References aKList::A, aKList::BI, aKList::F, aKList::LEF, and aKList::N2.
aKList SGP_SC_NORMAL (aKList theKList)
Definition at line 609 of file SGP_SuccessiveConvolutions.c.
References aKList::CM1, aKList::CM2, aKList::CM3, aKList::CM4, aKList::DE, aKList::E, aKList::H, aKList::H0, aKList::LEH, aKList::MIE, aKList::MIH, aKList::N1, aKList::output_file, aKList::write_output, and aKList::X.
aKList SGP_SC_OUTPUT (aKList theKList)
Definition at line 672 of file SGP_SuccessiveConvolutions.c.
References aKList::array_size, aKList::CM1, aKList::CM2, aKList::CM3, aKList::CM4, aKList::CN, aKList::D1, aKList::D2, aKList::D3, aKList::D4, aKList::DE, aKList::E, aKList::F, aKList::H, aKList::H0, aKList::LEF, aKList::LEH, aKList::MIE, aKList::MIF, aKList::MIH, aKList::N1, aKList::output_file, and aKList::write_output.
aKList SGP_SC_RESET (aKList theKList)
Definition at line 770 of file SGP_SuccessiveConvolutions.c.
References aKList::array_size, aKList::DE, aKList::DI, aKList::E, aKList::E0, aKList::F, aKList::LEF, aKList::MIE, aKList::MIF, aKList::N2, aKList::output_file, SGP_SC_INTERP(), aKList::U, and aKList::write_output.
aKList SGP_SC_SHRINK (aKList theKList)
Definition at line 926 of file SGP_SuccessiveConvolutions.c.
References aKList::DE, aKList::H, aKList::LEH, aKList::MIE, aKList::MIH, and aKList::shrink_tails_under.
aKList SGP_SC_ZERO (aKList theKList)
Definition at line 872 of file SGP_SuccessiveConvolutions.c.
References aKList::DE, aKList::F, aKList::F0, aKList::H, aKList::LEF, aKList::LEH, aKList::MIE, aKList::MIF, aKList::MIH, aKList::output_file, aKList::write_output, and aKList::X.
void SGP_SuccessiveConvolutions (float * u, long * n_bins_f, long * N2, long * n_bins_f_used, float * f_d_Gy, float * f_dd_Gy, float * f, float * f0, float * fdd, float * dfdd, float * d, bool * write_output, bool * shrink_tails, float * shrink_tails_under, bool * adjust_N2)
Definition at line 1047 of file SGP_SuccessiveConvolutions.c.
References aKList::A, aKList::adjust_N2, aKList::array_size, aKList::BI, aKList::CM1, aKList::CM2, aKList::CM3, aKList::CM4, aKList::CN, aKList::D1, aKList::D2, aKList::D3, aKList::D4, aKList::DE, aKList::DI, aKList::E, aKList::E0, aKList::F, aKList::F0, aKList::FINAL, aKList::H, aKList::H0, aKList::LEF, aKList::LEH, MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT, aKList::MIE, aKList::MIF, aKList::MIH, aKList::N1, aKList::N2, aKList::output_file, SGP_SC_FOLD(), SGP_SC_NORMAL(), SGP_SC_OUTPUT(), SGP_SC_SHRINK(), aKList::shrink_tails, aKList::shrink_tails_under, aKList::U, aKList::write_output, and aKList::X.