run.SPIFF		<-	function(	E.MeV.u,
					particle.no,
					fluence.cm2,
					material.no,
					RDD.model,
					RDD.parameters,
					ER.model,
					ER.parameters,
					gamma.model,
					gamma.parameters,
					N2,
					fluence.factor,
					write.output,
					shrink.tails,
					shrink.tails.under,
					adjust.N2,
					lethal.events.mode,
					verbose){

if(verbose){
	results.1	<-	AT.SC.get.f1.array.size(E.MeV.u = E.MeV.u,
								particle.no = particle.no,
								fluence.cm2 = fluence.cm2,
								material.no = material.no,
								RDD.model = RDD.model,
								RDD.parameters = RDD.parameters,
								ER.model = ER.model,
								ER.parameters = ER.parameters,
								N2 = N2)

	results.2	<-	AT.SC.get.f1(	E.MeV.u = E.MeV.u,
							particle.no = particle.no,
							fluence.cm2 = fluence.cm2,
							material.no = material.no,
							RDD.model = RDD.model,
							RDD.parameters = RDD.parameters,
							ER.model = ER.model,
							ER.parameters = ER.parameters,
							N2 = N2,
							n.bins.f1 = results.1$n.bins.f1,
							f1.parameters = results.1$f1.parameters)

	results.3	<-	AT.SC.get.f.array.size(	u = results.2$f.parameters[1],
								fluence.factor = fluence.factor,
								N2 = N2,
								n.bins.f1 = results.1$n.bins.f1,
								f1.d.Gy = results.2$f1$f1.d.Gy,
								f1.dd.Gy = results.2$f1$f1.dd.Gy,
								f1 = results.2$f1$f1)

	results.4	<-	AT.SC.get.f.start(	u = results.2$f.parameters[1],
								N2 = N2,
								n.bins.f1 = results.1$n.bins.f1,
								f1.d.Gy = results.2$f1$f1.d.Gy,
								f1.dd.Gy = results.2$f1$f1.dd.Gy,
								f1 = results.2$f1$f1,
								n.bins.f = results.3$n.bins.f)

	results.5	<-	AT.SC.SuccessiveConvolutions(	u = results.2$f.parameters[1],
									n.bins.f = results.3$n.bins.f,
									N2 = N2,
									n.bins.f.used = results.1$n.bins.f1,
									f.d.Gy = results.4$f.start.d.Gy,
									f.dd.Gy = results.4$f.start.dd.Gy,
									f = results.4$f.start,
									write.output = write.output,
									shrink.tails = shrink.tails,
									shrink.tails.under = shrink.tails.under,
									adjust.N2 = adjust.N2)

	return(	list(		E.MeV.u = E.MeV.u,
					particle.no = particle.no,
					fluence.cm2 = fluence.cm2,
					norm.fluence = results.2$norm.fluence,
					dose.contribution.Gy = results.2$dose.contribution.Gy,
					material.no = material.no,
					RDD.model = RDD.model,
					RDD.parameters = RDD.parameters,
					ER.model = ER.model,
					ER.parameters = ER.parameters,
					N2.set = N2,
					N2 = results.5$N2,
					f1.parameters = results.1$f1.parameters,
					f.parameters = results.2$f.parameters,
					n.bins.f1 = results.2$n.bins.f1,
					n.bins.f = results.3$n.bins.f,
					n.bins.f.used = results.5$n.bins.f.used,
					u.start = results.3$u.start,
					n.convolutions = results.3$n.convolutions,
					fluence.factor = fluence.factor,
					write.output = write.output,
					shrink.tails = shrink.tails,
					shrink.tails.under = shrink.tails.under,
					adjust.N2 = adjust.N2,
					d = results.5$d,
					f1 = results.2$f1,
					f.start = results.4,
					f0 = results.5$f0,
					f = results.5$f))
	}else{
		return(AT.run.SPIFF(	E.MeV.u 		= E.MeV.u,
							particle.no 	= particle.no,
							fluence.cm2 	= fluence.cm2,
							material.no 	= material.no,
							RDD.model 		= RDD.model,
							RDD.parameters 	= RDD.parameters,
							ER.model 		= ER.model,
							ER.parameters 	= ER.parameters,
							gamma.model		= gamma.model,
							gamma.parameters	= gamma.parameters,
							N2 			= N2,
							fluence.factor 	= fluence.factor,
							write.output 	= write.output,
							shrink.tails	= shrink.tails,
							shrink.tails.under = shrink.tails.under,
							adjust.N2 		= adjust.N2,
							lethal.events.mode	= lethal.events.mode)$results)
	}
}
