libSGP: SGP_Utils.c File Reference
SGP_Utils.c File Reference
#include "SGP_Utils.h"
#include "SGP_Data.h"
#include <stdio.h>
#include <stdlib.h>
#include <float.h>
#include <math.h>
#include <malloc.h>
#include <string.h>
#include <stdbool.h>
Defines
#define ITMAX 100
#define EPS 3.0e-7
#define FPMIN 1.0e-30
#define SIGN(a, b) ((b) >= 0.0 ? fabs(a) : -fabs(a))
#define MAXIT 60
#define UNUSED (-1.11e30)
Functions
void pmatchi (long *elements, long *n_elements, long *set, long *n_set, long *matches)
void pmatchc (char **elements, long *n_elements, char **set, long *n_set, long *matches)
void matchc (char *element, char **set, long *n_set, bool *matches)
void matchi (long *element, long *set, long *n_set, bool *matches)
void locate (float *xx, long *n, float *x, long *j)
void polint (float *xa, float *ya, long *n, float *x, float *y, float *dy)
void interp (float *xa, float *ya, long *n, long *n_pol, float *x, float *y, float *dy)
void getPSTARvalue (long *n, float *x, long *material_no, float *x_table, float *y_table, float *y)
float gammln (float xx)
void gcf (float *gammcf, float a, float x, float *gln)
void gser (float *gamser, float a, float x, float *gln)
float gammp (float a, float x)
float erff (float x)
void nrerror (char error_text[])
float zriddr (float(*func)(float, void *), void *params, float x1, float x2, float xacc)
Define Documentation
#define EPS 3.0e-7
Definition at line 248 of file SGP_Utils.c.
#define FPMIN 1.0e-30
Definition at line 249 of file SGP_Utils.c.
#define ITMAX 100
Definition at line 247 of file SGP_Utils.c.
#define MAXIT 60
Definition at line 333 of file SGP_Utils.c.
#define SIGN (a, b) ((b) >= 0.0 ? fabs(a) : -fabs(a))
Definition at line 332 of file SGP_Utils.c.
#define UNUSED (-1.11e30)
Definition at line 334 of file SGP_Utils.c.
Function Documentation
float erff (float x)
Definition at line 317 of file SGP_Utils.c.
References gammp().
float gammln (float xx)
Definition at line 231 of file SGP_Utils.c.
float gammp (float a, float x)
Definition at line 302 of file SGP_Utils.c.
References gcf(), and gser().
void gcf (float * gammcf, float a, float x, float * gln)
Definition at line 251 of file SGP_Utils.c.
References EPS, FPMIN, gammln(), and ITMAX.
void getPSTARvalue (long * n, float * x, long * material_no, float * x_table, float * y_table, float * y)
Definition at line 181 of file SGP_Utils.c.
References interp(), matchi(), pstar_data::material_no, pstar_data::n, and SGP_PSTAR_Data.
void gser (float * gamser, float a, float x, float * gln)
Definition at line 276 of file SGP_Utils.c.
References EPS, gammln(), and ITMAX.
void interp (float * xa, float * ya, long * n, long * n_pol, float * x, float * y, float * dy)
Definition at line 163 of file SGP_Utils.c.
References LMAX, LMIN, locate(), and polint().
void locate (float * xx, long * n, float * x, long * j)
Definition at line 105 of file SGP_Utils.c.
void matchc (char * element, char ** set, long * n_set, bool * matches)
Definition at line 76 of file SGP_Utils.c.
void matchi (long * element, long * set, long * n_set, bool * matches)
Definition at line 89 of file SGP_Utils.c.
void nrerror (char error_text[])
Definition at line 322 of file SGP_Utils.c.
void pmatchc (char ** elements, long * n_elements, char ** set, long * n_set, long * matches)
finds character elements in a set (n elements) and returns indices - only one (the first) match is reported per element a vector "matches" of length n_elements has to be provided
Definition at line 59 of file SGP_Utils.c.
void pmatchi (long * elements, long * n_elements, long * set, long * n_set, long * matches)
SGP_Utils.c
Created on: 28.07.2009 Author: greilich finds integer (32bit) elements in a set (n elements) and returns indices - only one (the first) match is reported per element a vector "matches" of length n_elements has to be provided
Definition at line 42 of file SGP_Utils.c.
void polint (float * xa, float * ya, long * n, float * x, float * y, float * dy)
Definition at line 126 of file SGP_Utils.c.
float zriddr (float(*)(float, void *) func, void * params, float x1, float x2, float xacc)
Definition at line 335 of file SGP_Utils.c.
References MAXIT, nrerror(), SIGN, and UNUSED.