libSGP: SGP_ParabolicCylinderFunction.c File Reference
SGP_ParabolicCylinderFunction.c File Reference
#include "SGP_ParabolicCylinderFunction.h"
#include "SGP_Constants.h"
#include <math.h>
#include <stdlib.h>
Functions
void SGP_Dyx (double *y, double *x, double *Dyx)
void SGP_fDyx (float *fy, float *fx, float *fDyx)
double d_sign (double *a, double *b)
int pbdv_ (double *v, double *x, double *dv, double *dp, double *pdf, double *pdd)
int dvsa_ (double *va, double *x, double *pd)
int dvla_ (double *va, double *x, double *pd)
int vvla_ (double *va, double *x, double *pv)
int gamma_ (double *x, double *ga)
void SGP_Funs (float *fz, float *fR0, float *fsigma, float *fni, float *funs)
Variables
static double c_b31 = 1.
static double c_b40 = 2.
Function Documentation
double d_sign (double * a, double * b)
Definition at line 86 of file SGP_ParabolicCylinderFunction.c.
int dvla_ (double * va, double * x, double * pd)
Definition at line 317 of file SGP_ParabolicCylinderFunction.c.
References gamma_(), pi, and vvla_().
int dvsa_ (double * va, double * x, double * pd)
Definition at line 253 of file SGP_ParabolicCylinderFunction.c.
References c_b40, gamma_(), and pi.
int gamma_ (double * x, double * ga)
Definition at line 421 of file SGP_ParabolicCylinderFunction.c.
References pi.
int pbdv_ (double * v, double * x, double * dv, double * dp, double * pdf, double * pdd)
Definition at line 94 of file SGP_ParabolicCylinderFunction.c.
References c_b31, d_sign(), dvla_(), and dvsa_().
void SGP_Dyx (double * y, double * x, double * Dyx)
Definition at line 60 of file SGP_ParabolicCylinderFunction.c.
References pbdv_().
void SGP_fDyx (float * fy, float * fx, float * fDyx)
Definition at line 74 of file SGP_ParabolicCylinderFunction.c.
References SGP_Dyx().
void SGP_Funs (float * fz, float * fR0, float * fsigma, float * fni, float * funs)
Definition at line 494 of file SGP_ParabolicCylinderFunction.c.
References gamma_(), pi, and SGP_Dyx().
int vvla_ (double * va, double * x, double * pv)
Definition at line 368 of file SGP_ParabolicCylinderFunction.c.
References dvla_(), gamma_(), and pi.
Variable Documentation
double c_b31 = 1. [static]
Definition at line 57 of file SGP_ParabolicCylinderFunction.c.
double c_b40 = 2. [static]
Definition at line 58 of file SGP_ParabolicCylinderFunction.c.