libSGP: SGParticle.h File Reference
SGParticle.h File Reference
Functions
void SGP_efficiency (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, long *N2=10, float *fluence_factor=1.0f, int *write_output=true, int *shrink_tails=true, float *shrink_tails_under=1e-30f, int *adjust_N2=true, float *results)
void SGP_efficiency_grid (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, long *N_runs, float *fluence_factor, bool *write_output, long *nX, float *grid_size_m, float *results)
void SGP_efficiency_Katz (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, float *results)
Function Documentation
void SGP_efficiency (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, long * N2 = 10, float * fluence_factor = 1.0f, int * write_output = true, int * shrink_tails = true, float * shrink_tails_under = 1e-30f, int * adjust_N2 = true, float * results)
Definition at line 24 of file SGParticle.c.
References SGP_get_gamma_response(), SGP_SC_get_f1(), SGP_SC_get_f1_array_size(), SGP_SC_get_f_array_size(), SGP_SC_get_f_start(), and SGP_SuccessiveConvolutions().
void SGP_efficiency_grid (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, long * N_runs, float * fluence_factor, bool * write_output, long * nX, float * grid_size_m, float * results)
Definition at line 246 of file SGParticle.c.
References FMAX, SGP_D_RDD_Gy(), SGP_gamma_response(), SGP_RDD_f1_parameters(), and SGP_SC_get_f1().
void SGP_efficiency_Katz (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, float * results)
Definition at line 616 of file SGParticle.c.