libSGP: SGP_Utils.h File Reference
SGP_Utils.h File Reference
#include <stdbool.h>
Defines
#define FMAX(a, b) (maxarg1=(a), maxarg2=(b), (maxarg1) > (maxarg2) ? (maxarg1) : (maxarg2))
#define FMIN(a, b) (minarg1=(a),minarg2=(b),(minarg1) < (minarg2) ? (minarg1) : (minarg2))
#define LMAX(a, b) (lmaxarg1=(a),lmaxarg2=(b),(lmaxarg1) > (lmaxarg2) ? (lmaxarg1) : (lmaxarg2))
#define LMIN(a, b) (lminarg1=(a),lminarg2=(b),(lminarg1) < (lminarg2) ? (lminarg1) : (lminarg2))
Functions
void pmatchi (long *elements, long *n_elements, long *set, long *n_set, long *matches)
void pmatchc (char **elements, long *n_elements, char **set, long *n_set, long *matches)
void matchc (char *element, char **set, long *n_set, bool *matches)
void matchi (long *element, long *set, long *n_set, bool *matches)
void locate (float *xx, long *n, float *x, long *j)
void polint (float *xa, float *ya, long *n, float *x, float *y, float *dy)
void interp (float *xa, float *ya, long *n, long *n_pol, float *x, float *y, float *dy)
void getPSTARvalue (long *n, float *x, long *material_no, float *x_table, float *y_table, float *y)
float gammln (float xx)
void gcf (float *gammcf, float a, float x, float *gln)
void gser (float *gamser, float a, float x, float *gln)
float gammp (float a, float x)
float erff (float x)
void nrerror (char error_text[])
float zriddr (float(*func)(float, void *), void *params, float x1, float x2, float xacc)
Variables
static float maxarg1
static float maxarg2
static float minarg1
static float minarg2
static long lmaxarg1
static long lmaxarg2
static long lminarg1
static long lminarg2
Define Documentation
#define FMAX (a, b) (maxarg1=(a), maxarg2=(b), (maxarg1) > (maxarg2) ? (maxarg1) : (maxarg2))
Definition at line 8 of file SGP_Utils.h.
#define FMIN (a, b) (minarg1=(a),minarg2=(b),(minarg1) < (minarg2) ? (minarg1) : (minarg2))
Definition at line 12 of file SGP_Utils.h.
#define LMAX (a, b) (lmaxarg1=(a),lmaxarg2=(b),(lmaxarg1) > (lmaxarg2) ? (lmaxarg1) : (lmaxarg2))
Definition at line 16 of file SGP_Utils.h.
#define LMIN (a, b) (lminarg1=(a),lminarg2=(b),(lminarg1) < (lminarg2) ? (lminarg1) : (lminarg2))
Definition at line 20 of file SGP_Utils.h.
Function Documentation
float erff (float x)
Definition at line 317 of file SGP_Utils.c.
References gammp().
float gammln (float xx)
Definition at line 231 of file SGP_Utils.c.
float gammp (float a, float x)
Definition at line 302 of file SGP_Utils.c.
References gcf(), and gser().
void gcf (float * gammcf, float a, float x, float * gln)
Definition at line 251 of file SGP_Utils.c.
References EPS, FPMIN, gammln(), and ITMAX.
void getPSTARvalue (long * n, float * x, long * material_no, float * x_table, float * y_table, float * y)
Definition at line 181 of file SGP_Utils.c.
References interp(), matchi(), pstar_data::material_no, pstar_data::n, and SGP_PSTAR_Data.
void gser (float * gamser, float a, float x, float * gln)
Definition at line 276 of file SGP_Utils.c.
References EPS, gammln(), and ITMAX.
void interp (float * xa, float * ya, long * n, long * n_pol, float * x, float * y, float * dy)
Definition at line 163 of file SGP_Utils.c.
References LMAX, LMIN, locate(), and polint().
void locate (float * xx, long * n, float * x, long * j)
Definition at line 105 of file SGP_Utils.c.
void matchc (char * element, char ** set, long * n_set, bool * matches)
Definition at line 76 of file SGP_Utils.c.
void matchi (long * element, long * set, long * n_set, bool * matches)
Definition at line 89 of file SGP_Utils.c.
void nrerror (char error_text[])
Definition at line 322 of file SGP_Utils.c.
void pmatchc (char ** elements, long * n_elements, char ** set, long * n_set, long * matches)
finds character elements in a set (n elements) and returns indices - only one (the first) match is reported per element a vector "matches" of length n_elements has to be provided
Definition at line 59 of file SGP_Utils.c.
void pmatchi (long * elements, long * n_elements, long * set, long * n_set, long * matches)
SGP_Utils.c
Created on: 28.07.2009 Author: greilich finds integer (32bit) elements in a set (n elements) and returns indices - only one (the first) match is reported per element a vector "matches" of length n_elements has to be provided
Definition at line 42 of file SGP_Utils.c.
void polint (float * xa, float * ya, long * n, float * x, float * y, float * dy)
Definition at line 126 of file SGP_Utils.c.
float zriddr (float(*)(float, void *) func, void * params, float x1, float x2, float xacc)
Definition at line 335 of file SGP_Utils.c.
References MAXIT, nrerror(), SIGN, and UNUSED.
Variable Documentation
long lmaxarg1 [static]
Definition at line 14 of file SGP_Utils.h.
long lmaxarg2 [static]
Definition at line 15 of file SGP_Utils.h.
long lminarg1 [static]
Definition at line 18 of file SGP_Utils.h.
long lminarg2 [static]
Definition at line 19 of file SGP_Utils.h.
float maxarg1 [static]
Definition at line 6 of file SGP_Utils.h.
float maxarg2 [static]
Definition at line 7 of file SGP_Utils.h.
float minarg1 [static]
Definition at line 10 of file SGP_Utils.h.
float minarg2 [static]
Definition at line 11 of file SGP_Utils.h.