libSGP: SGP_FileOperations.c File Reference
SGP_FileOperations.c File Reference
#include "SGP_FileOperations.h"
#include "SGP_Utils.h"
#include <stdlib.h>
Functions
void SGP_browseInput (char *fileName, long *nLines, long *n_gamma_parameter)
void SGP_browseInputS (char **fileName, long *nLines, long *n_gamma_parameter)
void SGP_readInput (char *fileName, long *nLines, long *n_gamma_parameter, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *slab_no, float *parameter, long *N2, char *material_name, long *n_slabs, long *gamma_model, float *gamma_parameter)
void SGP_readInputS (char **fileName, long *nLines, long *n_gamma_parameter, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *slab_no, float *parameter, long *N2, char **material_name, long *n_slabs, long *gamma_model, float *gamma_parameter)
void SGP_browseSpectrum (char *fileName, long *nLines)
void SGP_browseSpectrumS (char **fileName, long *nLines)
void SGP_readSpectrum (char *fileName, long *nLines, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *slab_no)
void SGP_readSpectrumS (char **fileName, long *nLines, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *slab_no)
Function Documentation
void SGP_browseInput (char * fileName, long * nLines, long * n_gamma_parameter)
Definition at line 14 of file SGP_FileOperations.c.
void SGP_browseInputS (char ** fileName, long * nLines, long * n_gamma_parameter)
Definition at line 55 of file SGP_FileOperations.c.
References SGP_browseInput().
void SGP_browseSpectrum (char * fileName, long * nLines)
Definition at line 229 of file SGP_FileOperations.c.
void SGP_browseSpectrumS (char ** fileName, long * nLines)
Definition at line 250 of file SGP_FileOperations.c.
References SGP_browseSpectrum().
void SGP_readInput (char * fileName, long * nLines, long * n_gamma_parameter, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * slab_no, float * parameter, long * N2, char * material_name, long * n_slabs, long * gamma_model, float * gamma_parameter)
Definition at line 64 of file SGP_FileOperations.c.
References LMAX.
void SGP_readInputS (char ** fileName, long * nLines, long * n_gamma_parameter, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * slab_no, float * parameter, long * N2, char ** material_name, long * n_slabs, long * gamma_model, float * gamma_parameter)
Definition at line 200 of file SGP_FileOperations.c.
References SGP_readInput().
void SGP_readSpectrum (char * fileName, long * nLines, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * slab_no)
Definition at line 258 of file SGP_FileOperations.c.
void SGP_readSpectrumS (char ** fileName, long * nLines, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * slab_no)
Definition at line 295 of file SGP_FileOperations.c.
References SGP_readSpectrum().