libSGP: SGP_Functions.c File Reference
SGP_Functions.c File Reference
#include "SGP_Functions.h"
#include "SGP_Constants.h"
#include "SGP_Data.h"
#include "SGP_Utils.h"
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Defines
#define matchIt
Functions
void SGP_Particle_Properties (long *particle_no, char **particle_name, char **USRTRACK_name, char **element_name, long *Z, long *A, float *mass)
void SGP_getMaterialData (long *n, long *material_no, float *density_g_cm3, float *electron_density_m3, float *I_eV, float *alpha_g_cm2_MeV, float *p_MeV, float *m_g_cm2)
void SGP_density_g_cm3 (long *n, char *material_name, float *density_g_cm3)
void SGP_density_g_cm3S (char **material_name, float *density_g_cm3)
void SGP_electron_density_m3 (long *n, char *material_name, float *electron_density_m3)
void SGP_electron_density_m3S (char **material_name, float *electron_density_m3)
void SGP_alpha_g_cm2_MeV (long *n, char *material_name, float *alpha_g_cm2_MeV)
void SGP_p_MeV (long *n, char *material_name, float *p_MeV)
void SGP_m_g_cm2 (long *n, char *material_name, float *m_g_cm2)
void SGP_LET_MeV_cm2_g (long *n, float *E_MeV_u, long *particle_no, long *material_no, float *LET_MeV_cm2_g)
void SGP_LET_keV_um (long *n, float *E_MeV_u, long *particle_no, long *material_no, float *LET_keV_um)
void SGP_CSDA_range_g_cm2 (long *n, float *E_MeV_u, long *particle_no, long *material_no, float *CSDA_range_g_cm2)
void SGP_E_MeV_from_CDSA_range (long *n, float *CSDA_range_g_cm2, long *particle_no, long *material_no, float *E_MeV)
void SGP_E_MeV_from_LET (long *n, float *LET_MeV_cm2_g, long *particle_no, long *material_no, float *E_MeV)
void SGP_beta_from_particle_no (long *n, float *E_MeV_u, long *particle_no, float *beta)
void SGP_beta_from_mass (long *n, float *E_MeV_u, float *mass, float *beta)
void SGP_E_from_beta_and_mass (long *n, float *beta, float *mass, float *E_MeV_u)
void SGP_E_from_beta_and_particle_no (long *n, float *beta, long *particle_no, float *E_MeV_u)
void SGP_effective_charge_from_particle_no (long *n, float *E_MeV_u, long *particle_no, float *effective_charge)
void SGP_effective_charge_from_beta (long *n, float *beta, long *Z, float *effective_charge)
void SGP_scaled_energy (long *n, float *E_MeV_u, long *particle_no, float *scaled_energy)
void SGP_max_E_transfer_MeV (long *n, float *E_MeV_u, long *particle_no, float *max_E_transfer_MeV)
void SGP_max_electron_range_m (long *n, float *E_MeV_u, long *particle_no, long *material_no, long *er_model, float *max_electron_range_m)
void SGP_Bohr_Energy_Straggling_g_cm2 (long *n, char **material_name, float *dsE2dz)
void SGP_Z_from_particle_no (long *n, long *particle_no, long *Z)
Define Documentation
#define matchIt
Value:
long    n_mat   = 1;                                                                    \
                                                pmatchc(        &material_name,                                                         \
                                                                        &n_mat,                                                                         \
                                                                        SGP_Material_Data.material_name,                        \
                                                                        &SGP_Material_Data.n,                                           \
                                                                        &match);
Definition at line 75 of file SGP_Functions.c.
Function Documentation
void SGP_alpha_g_cm2_MeV (long * n, char * material_name, float * alpha_g_cm2_MeV)
Definition at line 115 of file SGP_Functions.c.
References material_data::alpha_g_cm2_MeV, matchIt, and SGP_Material_Data.
void SGP_beta_from_mass (long * n, float * E_MeV_u, float * mass, float * beta)
Definition at line 289 of file SGP_Functions.c.
References proton_mass_MeV_c2.
void SGP_beta_from_particle_no (long * n, float * E_MeV_u, long * particle_no, float * beta)
Definition at line 261 of file SGP_Functions.c.
References particle_data::mass, particle_data::n, particle_data::particle_no, pmatchi(), SGP_beta_from_mass(), and SGP_Particle_Data.
void SGP_Bohr_Energy_Straggling_g_cm2 (long * n, char ** material_name, float * dsE2dz)
Definition at line 629 of file SGP_Functions.c.
References e0_F_m, e_C, m_to_cm, MeV_to_J, pi, and SGP_electron_density_m3().
void SGP_CSDA_range_g_cm2 (long * n, float * E_MeV_u, long * particle_no, long * material_no, float * CSDA_range_g_cm2)
Definition at line 227 of file SGP_Functions.c.
References getPSTARvalue(), pstar_data::kin_E_MeV, pstar_data::range_cdsa_g_cm2, and SGP_PSTAR_Data.
void SGP_density_g_cm3 (long * n, char * material_name, float * density_g_cm3)
Definition at line 82 of file SGP_Functions.c.
References material_data::density_g_cm3, matchIt, and SGP_Material_Data.
void SGP_density_g_cm3S (char ** material_name, float * density_g_cm3)
Definition at line 90 of file SGP_Functions.c.
References SGP_density_g_cm3().
void SGP_E_from_beta_and_mass (long * n, float * beta, float * mass, float * E_MeV_u)
Definition at line 308 of file SGP_Functions.c.
References proton_mass_MeV_c2.
void SGP_E_from_beta_and_particle_no (long * n, float * beta, long * particle_no, float * E_MeV_u)
Definition at line 327 of file SGP_Functions.c.
References particle_data::mass, particle_data::n, particle_data::particle_no, pmatchi(), SGP_E_from_beta_and_mass(), and SGP_Particle_Data.
void SGP_E_MeV_from_CDSA_range (long * n, float * CSDA_range_g_cm2, long * particle_no, long * material_no, float * E_MeV)
Definition at line 236 of file SGP_Functions.c.
References getPSTARvalue(), pstar_data::kin_E_MeV, pstar_data::range_cdsa_g_cm2, and SGP_PSTAR_Data.
void SGP_E_MeV_from_LET (long * n, float * LET_MeV_cm2_g, long * particle_no, long * material_no, float * E_MeV)
Definition at line 246 of file SGP_Functions.c.
References getPSTARvalue(), pstar_data::kin_E_MeV, SGP_PSTAR_Data, and pstar_data::stp_pow_el_MeV_cm2_g.
void SGP_effective_charge_from_beta (long * n, float * beta, long * Z, float * effective_charge)
Definition at line 393 of file SGP_Functions.c.
void SGP_effective_charge_from_particle_no (long * n, float * E_MeV_u, long * particle_no, float * effective_charge)
Definition at line 356 of file SGP_Functions.c.
References particle_data::n, particle_data::particle_no, pmatchi(), SGP_beta_from_particle_no(), SGP_effective_charge_from_beta(), SGP_Particle_Data, and particle_data::Z.
void SGP_electron_density_m3 (long * n, char * material_name, float * electron_density_m3)
Definition at line 98 of file SGP_Functions.c.
References material_data::electron_density_m3, matchIt, and SGP_Material_Data.
void SGP_electron_density_m3S (char ** material_name, float * electron_density_m3)
Definition at line 106 of file SGP_Functions.c.
References SGP_electron_density_m3().
void SGP_getMaterialData (long * n, long * material_no, float * density_g_cm3, float * electron_density_m3, float * I_eV, float * alpha_g_cm2_MeV, float * p_MeV, float * m_g_cm2)
Definition at line 45 of file SGP_Functions.c.
References material_data::alpha_g_cm2_MeV, material_data::density_g_cm3, material_data::electron_density_m3, material_data::I_eV, material_data::m_g_cm2, material_data::material_no, material_data::n, material_data::p_MeV, pmatchi(), and SGP_Material_Data.
void SGP_LET_keV_um (long * n, float * E_MeV_u, long * particle_no, long * material_no, float * LET_keV_um)
Definition at line 200 of file SGP_Functions.c.
References material_data::density_g_cm3, material_data::material_no, material_data::n, pmatchi(), SGP_LET_MeV_cm2_g(), and SGP_Material_Data.
void SGP_LET_MeV_cm2_g (long * n, float * E_MeV_u, long * particle_no, long * material_no, float * LET_MeV_cm2_g)
Definition at line 145 of file SGP_Functions.c.
References getPSTARvalue(), pstar_data::kin_E_MeV, SGP_effective_charge_from_particle_no(), SGP_PSTAR_Data, SGP_scaled_energy(), and pstar_data::stp_pow_el_MeV_cm2_g.
void SGP_m_g_cm2 (long * n, char * material_name, float * m_g_cm2)
Definition at line 131 of file SGP_Functions.c.
References material_data::m_g_cm2, matchIt, and SGP_Material_Data.
void SGP_max_E_transfer_MeV (long * n, float * E_MeV_u, long * particle_no, float * max_E_transfer_MeV)
Definition at line 457 of file SGP_Functions.c.
References electron_mass_MeV_c2, proton_mass_MeV_c2, and SGP_beta_from_particle_no().
void SGP_max_electron_range_m (long * n, float * E_MeV_u, long * particle_no, long * material_no, long * er_model, float * max_electron_range_m)
Definition at line 547 of file SGP_Functions.c.
References material_data::density_g_cm3, electron_mass_MeV_c2, ER_ButtsKatz, ER_Geiss, ER_Scholz, ER_Waligorski, particle_data::mass, particle_data::n, particle_data::particle_no, pmatchi(), proton_mass_MeV_c2, SGP_Material_Data, and SGP_Particle_Data.
void SGP_p_MeV (long * n, char * material_name, float * p_MeV)
Definition at line 123 of file SGP_Functions.c.
References matchIt, material_data::p_MeV, and SGP_Material_Data.
void SGP_Particle_Properties (long * particle_no, char ** particle_name, char ** USRTRACK_name, char ** element_name, long * Z, long * A, float * mass)
Definition at line 23 of file SGP_Functions.c.
References particle_data::A, particle_data::element_name, particle_data::mass, particle_data::particle_name, SGP_Particle_Data, particle_data::USRTRACK_name, and particle_data::Z.
void SGP_scaled_energy (long * n, float * E_MeV_u, long * particle_no, float * scaled_energy)
Definition at line 411 of file SGP_Functions.c.
References particle_data::mass, particle_data::n, particle_data::particle_no, pmatchi(), proton_mass_MeV_c2, and SGP_Particle_Data.
void SGP_Z_from_particle_no (long * n, long * particle_no, long * Z)
Definition at line 649 of file SGP_Functions.c.
References particle_data::n, particle_data::particle_no, pmatchi(), SGP_Particle_Data, and particle_data::Z.