/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AmTrack_AmTrackTestGUI */

#ifndef _Included_AmTrack_AmTrackTestGUI
#define _Included_AmTrack_AmTrackTestGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_DEFAULT
#define AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_SET
#define AmTrack_AmTrackTestGUI_FOCUS_TRAVERSABLE_SET 2L
#undef AmTrack_AmTrackTestGUI_TOP_ALIGNMENT
#define AmTrack_AmTrackTestGUI_TOP_ALIGNMENT 0.0f
#undef AmTrack_AmTrackTestGUI_CENTER_ALIGNMENT
#define AmTrack_AmTrackTestGUI_CENTER_ALIGNMENT 0.5f
#undef AmTrack_AmTrackTestGUI_BOTTOM_ALIGNMENT
#define AmTrack_AmTrackTestGUI_BOTTOM_ALIGNMENT 1.0f
#undef AmTrack_AmTrackTestGUI_LEFT_ALIGNMENT
#define AmTrack_AmTrackTestGUI_LEFT_ALIGNMENT 0.0f
#undef AmTrack_AmTrackTestGUI_RIGHT_ALIGNMENT
#define AmTrack_AmTrackTestGUI_RIGHT_ALIGNMENT 1.0f
#undef AmTrack_AmTrackTestGUI_serialVersionUID
#define AmTrack_AmTrackTestGUI_serialVersionUID -7644114512714619750i64
#undef AmTrack_AmTrackTestGUI_serialVersionUID
#define AmTrack_AmTrackTestGUI_serialVersionUID 4613797578919906343i64
#undef AmTrack_AmTrackTestGUI_INCLUDE_SELF
#define AmTrack_AmTrackTestGUI_INCLUDE_SELF 1L
#undef AmTrack_AmTrackTestGUI_SEARCH_HEAVYWEIGHTS
#define AmTrack_AmTrackTestGUI_SEARCH_HEAVYWEIGHTS 1L
#undef AmTrack_AmTrackTestGUI_NOT_OBSCURED
#define AmTrack_AmTrackTestGUI_NOT_OBSCURED 0L
#undef AmTrack_AmTrackTestGUI_PARTIALLY_OBSCURED
#define AmTrack_AmTrackTestGUI_PARTIALLY_OBSCURED 1L
#undef AmTrack_AmTrackTestGUI_COMPLETELY_OBSCURED
#define AmTrack_AmTrackTestGUI_COMPLETELY_OBSCURED 2L
#undef AmTrack_AmTrackTestGUI_WHEN_FOCUSED
#define AmTrack_AmTrackTestGUI_WHEN_FOCUSED 0L
#undef AmTrack_AmTrackTestGUI_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define AmTrack_AmTrackTestGUI_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef AmTrack_AmTrackTestGUI_WHEN_IN_FOCUSED_WINDOW
#define AmTrack_AmTrackTestGUI_WHEN_IN_FOCUSED_WINDOW 2L
#undef AmTrack_AmTrackTestGUI_UNDEFINED_CONDITION
#define AmTrack_AmTrackTestGUI_UNDEFINED_CONDITION -1L
#undef AmTrack_AmTrackTestGUI_IS_DOUBLE_BUFFERED
#define AmTrack_AmTrackTestGUI_IS_DOUBLE_BUFFERED 0L
#undef AmTrack_AmTrackTestGUI_ANCESTOR_USING_BUFFER
#define AmTrack_AmTrackTestGUI_ANCESTOR_USING_BUFFER 1L
#undef AmTrack_AmTrackTestGUI_IS_PAINTING_TILE
#define AmTrack_AmTrackTestGUI_IS_PAINTING_TILE 2L
#undef AmTrack_AmTrackTestGUI_IS_OPAQUE
#define AmTrack_AmTrackTestGUI_IS_OPAQUE 3L
#undef AmTrack_AmTrackTestGUI_KEY_EVENTS_ENABLED
#define AmTrack_AmTrackTestGUI_KEY_EVENTS_ENABLED 4L
#undef AmTrack_AmTrackTestGUI_FOCUS_INPUTMAP_CREATED
#define AmTrack_AmTrackTestGUI_FOCUS_INPUTMAP_CREATED 5L
#undef AmTrack_AmTrackTestGUI_ANCESTOR_INPUTMAP_CREATED
#define AmTrack_AmTrackTestGUI_ANCESTOR_INPUTMAP_CREATED 6L
#undef AmTrack_AmTrackTestGUI_WIF_INPUTMAP_CREATED
#define AmTrack_AmTrackTestGUI_WIF_INPUTMAP_CREATED 7L
#undef AmTrack_AmTrackTestGUI_ACTIONMAP_CREATED
#define AmTrack_AmTrackTestGUI_ACTIONMAP_CREATED 8L
#undef AmTrack_AmTrackTestGUI_CREATED_DOUBLE_BUFFER
#define AmTrack_AmTrackTestGUI_CREATED_DOUBLE_BUFFER 9L
#undef AmTrack_AmTrackTestGUI_IS_PRINTING
#define AmTrack_AmTrackTestGUI_IS_PRINTING 11L
#undef AmTrack_AmTrackTestGUI_IS_PRINTING_ALL
#define AmTrack_AmTrackTestGUI_IS_PRINTING_ALL 12L
#undef AmTrack_AmTrackTestGUI_IS_REPAINTING
#define AmTrack_AmTrackTestGUI_IS_REPAINTING 13L
#undef AmTrack_AmTrackTestGUI_WRITE_OBJ_COUNTER_FIRST
#define AmTrack_AmTrackTestGUI_WRITE_OBJ_COUNTER_FIRST 14L
#undef AmTrack_AmTrackTestGUI_RESERVED_1
#define AmTrack_AmTrackTestGUI_RESERVED_1 15L
#undef AmTrack_AmTrackTestGUI_RESERVED_2
#define AmTrack_AmTrackTestGUI_RESERVED_2 16L
#undef AmTrack_AmTrackTestGUI_RESERVED_3
#define AmTrack_AmTrackTestGUI_RESERVED_3 17L
#undef AmTrack_AmTrackTestGUI_RESERVED_4
#define AmTrack_AmTrackTestGUI_RESERVED_4 18L
#undef AmTrack_AmTrackTestGUI_RESERVED_5
#define AmTrack_AmTrackTestGUI_RESERVED_5 19L
#undef AmTrack_AmTrackTestGUI_RESERVED_6
#define AmTrack_AmTrackTestGUI_RESERVED_6 20L
#undef AmTrack_AmTrackTestGUI_WRITE_OBJ_COUNTER_LAST
#define AmTrack_AmTrackTestGUI_WRITE_OBJ_COUNTER_LAST 21L
#undef AmTrack_AmTrackTestGUI_REQUEST_FOCUS_DISABLED
#define AmTrack_AmTrackTestGUI_REQUEST_FOCUS_DISABLED 22L
#undef AmTrack_AmTrackTestGUI_INHERITS_POPUP_MENU
#define AmTrack_AmTrackTestGUI_INHERITS_POPUP_MENU 23L
#undef AmTrack_AmTrackTestGUI_OPAQUE_SET
#define AmTrack_AmTrackTestGUI_OPAQUE_SET 24L
#undef AmTrack_AmTrackTestGUI_AUTOSCROLLS_SET
#define AmTrack_AmTrackTestGUI_AUTOSCROLLS_SET 25L
#undef AmTrack_AmTrackTestGUI_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define AmTrack_AmTrackTestGUI_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef AmTrack_AmTrackTestGUI_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define AmTrack_AmTrackTestGUI_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     AmTrack_AmTrackTestGUI
 * Method:    ATconvertBeamParameters
 * Signature: (FFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_AmTrack_AmTrackTestGUI_ATconvertBeamParameters
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
