libSGP: SGParticle.c File Reference
SGParticle.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "SGP_Constants.h"
#include "SGP_Data.h"
#include "SGP_Utils.h"
#include "SGP_Functions.h"
#include "SGP_RDD.h"
#include "SGP_SuccessiveConvolutions.h"
#include "SGP_GammaResponse.h"
#include "SGP_FileOperations.h"
#include "SGP_ParabolicCylinderFunction.h"
#include "SGP_Transport.h"
#include <gsl/gsl_rng.h>
#include <gsl/gsl_integration.h>
Defines
#define _WINDOWS
#define _S
#define _SOLVER
Functions
void SGP_efficiency (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, long *N2, float *fluence_factor, int *write_output, int *shrink_tails, float *shrink_tails_under, int *adjust_N2, float *results)
void SGP_efficiency_grid (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, long *N_runs, float *fluence_factor, bool *write_output, long *nX, float *grid_size_m, float *results)
void SGP_efficiency_Katz (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *RDD_model, float *RDD_parameters, long *ER_model, float *ER_parameters, long *gamma_model, float *gamma_parameters, float *results)
Define Documentation
#define _S
Definition at line 6 of file SGParticle.c.
#define _SOLVER
Definition at line 8 of file SGParticle.c.
#define _WINDOWS
Definition at line 5 of file SGParticle.c.
Function Documentation
void SGP_efficiency (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, long * N2, float * fluence_factor, int * write_output, int * shrink_tails, float * shrink_tails_under, int * adjust_N2, float * results)
Definition at line 24 of file SGParticle.c.
References SGP_get_gamma_response(), SGP_SC_get_f1(), SGP_SC_get_f1_array_size(), SGP_SC_get_f_array_size(), SGP_SC_get_f_start(), and SGP_SuccessiveConvolutions().
void SGP_efficiency_grid (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, long * N_runs, float * fluence_factor, bool * write_output, long * nX, float * grid_size_m, float * results)
Definition at line 246 of file SGParticle.c.
References FMAX, SGP_D_RDD_Gy(), SGP_gamma_response(), SGP_RDD_f1_parameters(), and SGP_SC_get_f1().
void SGP_efficiency_Katz (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * RDD_model, float * RDD_parameters, long * ER_model, float * ER_parameters, long * gamma_model, float * gamma_parameters, float * results)
Definition at line 616 of file SGParticle.c.