libSGP: test.c File Reference
test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <math.h>
#include <stdbool.h>
#include <string.h>
Functions
void testRDD ()
int main ()
Function Documentation
int main ()
Definition at line 571 of file test.c.
References testRDD().
void testRDD ()
Definition at line 127 of file test.c.
References SGP_D_RDD_Gy(), SGP_SC_get_f1(), SGP_SC_get_f1_array_size(), SGP_SC_get_f_array_size(), SGP_SC_get_f_start(), and SGP_SuccessiveConvolutions().