libSGP: SGP_RDD.c File Reference
SGP_RDD.c File Reference
#include "SGP_RDD.h"
#include "SGP_Constants.h"
#include "SGP_Data.h"
#include "SGP_Utils.h"
#include "SGP_Functions.h"
#include <gsl/gsl_integration.h>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_sf_exp.h>
#include <gsl/gsl_sf_log.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_const_mksa.h>
#include <gsl/gsl_const_num.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_roots.h>
#include <gsl/gsl_sf_hyperg.h>
Data Structures
struct SGP_D_RDD_Gy_parameters
Functions
float SGP_RDD_Katz_point_kernel (float *x, float *alpha)
void SGP_RDD_Katz_point_kernelS (int *n, float *x, float *alpha, float *f)
float SGP_RDD_Katz_point_coeff_Gy (float *C_J_m, float *Z_eff, float *beta, float *alpha, float *density_kg_m3, float *r_max_m)
float SGP_RDD_Katz_point_Gy (float *r_m, float *alpha, float *r_max_m, float *Katz_point_coeff_Gy)
void SGP_RDD_Katz_point_GyS (int *n, float *r_m, float *alpha, float *r_max_m, float *Katz_point_coeff_Gy, float *D)
float SGP_RDD_Katz_dEdx_kernel (float *x, float *alpha)
void SGP_RDD_Katz_dEdx_kernelS (int *n, float *x, float *alpha, float *f)
double SGP_RDD_Katz_dEdx_integrand (double x, void *params)
float SGP_RDD_Katz_dEdx_coeff_J_m (float *r_max_m, float *density_kg_m3, float *Katz_point_coeff_Gy)
float SGP_RDD_Katz_dEdx_J_m (float *alpha, float *r_min_m, float *r_max_m, float *Katz_dEdx_coeff_J_m)
float SGP_RDD_Katz_site_Gy (float *r_m, float *alpha, float *r_min_m, float *r_max_m, float *LET_J_m, float *density_kg_m3, float *Katz_dEdx_J_m, float *Katz_point_coeff_Gy)
void SGP_RDD_Katz_site_GyS (int *n, float *r_m, float *alpha, float *r_min_m, float *r_max_m, float *LET_J_m, float *density_kg_m3, float *Katz_dEdx_J_m, float *Katz_point_coeff_Gy, float *D_Gy)
float geometryFunctionPhi (float *r0_m, float *a0_m, float *r_m)
float SGP_RDD_Katz_ext_kernel_Gy (float *t_m, float *r_m, float *a0_m, float *alpha, float *r_min_m, float *r_max_m, float *Katz_point_coeff_Gy)
void SGP_RDD_Katz_ext_kernel_GyS (int *n, float *t_m, float *r_m, float *a0_m, float *alpha, float *r_min_m, float *r_max_m, float *Katz_point_coeff_Gy, float *D_Gy)
double SGP_RDD_Katz_ext_integrand_Gy (double t_m, void *params)
float SGP_RDD_Katz_ext_Gy (float *r_m, float *a0_m, float *alpha, float *r_min_m, float *r_max_m, float *Katz_point_coeff_Gy)
void SGP_RDD_Katz_ext_GyS (int *n, float *r_m, float *a0_m, float *alpha, float *r_min_m, float *r_max_m, float *Katz_point_coeff_Gy, float *D_Gy)
void SGP_RDD_f1_parameters (float *E_MeV_u, long *particle_no, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, float *f1_parameters)
void SGP_D_RDD_Gy (long *n, float *r_m, float *E_MeV_u, long *particle_no, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, float *D_RDD_Gy)
float SGP_D_RDD_Gy_solver (float r, void *params)
void SGP_r_RDD_m (long *n, float *D_RDD_Gy, float *E_MeV_u, long *particle_no, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, float *r_RDD_m)
Function Documentation
float geometryFunctionPhi (float * r0_m, float * a0_m, float * r_m)
Definition at line 105 of file SGP_RDD.c.
void SGP_D_RDD_Gy (long * n, float * r_m, float * E_MeV_u, long * particle_no, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, float * D_RDD_Gy)
Definition at line 412 of file SGP_RDD.c.
References electron_mass_MeV_c2, FMAX, RDD_ExtTarget, RDD_Geiss, RDD_KatzPoint, RDD_Site, RDD_Test, SGP_beta_from_particle_no(), SGP_effective_charge_from_beta(), SGP_getMaterialData(), SGP_RDD_f1_parameters(), SGP_RDD_Katz_ext_Gy(), SGP_RDD_Katz_point_coeff_Gy(), SGP_RDD_Katz_point_Gy(), and SGP_Z_from_particle_no().
float SGP_D_RDD_Gy_solver (float r, void * params)
Definition at line 590 of file SGP_RDD.c.
void SGP_r_RDD_m (long * n, float * D_RDD_Gy, float * E_MeV_u, long * particle_no, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, float * r_RDD_m)
Definition at line 610 of file SGP_RDD.c.
References SGP_D_RDD_Gy_parameters::D0, SGP_D_RDD_Gy_parameters::D_RDD_Gy, SGP_D_RDD_Gy_parameters::E_MeV_u, electron_mass_MeV_c2, SGP_D_RDD_Gy_parameters::er_model, SGP_D_RDD_Gy_parameters::er_parameter, FMAX, SGP_D_RDD_Gy_parameters::material_no, SGP_D_RDD_Gy_parameters::n, SGP_D_RDD_Gy_parameters::particle_no, RDD_ExtTarget, RDD_Geiss, RDD_KatzPoint, SGP_D_RDD_Gy_parameters::rdd_model, SGP_D_RDD_Gy_parameters::rdd_parameter, RDD_Site, RDD_Test, SGP_beta_from_particle_no(), SGP_D_RDD_Gy(), SGP_D_RDD_Gy_solver(), SGP_effective_charge_from_beta(), SGP_getMaterialData(), SGP_RDD_f1_parameters(), SGP_RDD_Katz_point_coeff_Gy(), SGP_Z_from_particle_no(), and zriddr().
void SGP_RDD_f1_parameters (float * E_MeV_u, long * particle_no, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, float * f1_parameters)
Definition at line 232 of file SGP_RDD.c.
References c_cm_s, e_esu, electron_mass_g, electron_mass_MeV_c2, m_to_cm, MeV_g_to_J_kg, MeV_to_J, pi, RDD_ExtTarget, RDD_Geiss, RDD_KatzPoint, RDD_Site, RDD_Test, SGP_beta_from_particle_no(), SGP_effective_charge_from_beta(), SGP_getMaterialData(), SGP_LET_MeV_cm2_g(), SGP_max_electron_range_m(), SGP_RDD_Katz_dEdx_coeff_J_m(), SGP_RDD_Katz_dEdx_J_m(), SGP_RDD_Katz_ext_Gy(), SGP_RDD_Katz_point_coeff_Gy(), SGP_RDD_Katz_point_Gy(), SGP_RDD_Katz_site_Gy(), and SGP_Z_from_particle_no().
float SGP_RDD_Katz_dEdx_coeff_J_m (float * r_max_m, float * density_kg_m3, float * Katz_point_coeff_Gy) [inline]
Definition at line 71 of file SGP_RDD.c.
double SGP_RDD_Katz_dEdx_integrand (double x, void * params)
Definition at line 65 of file SGP_RDD.c.
References SGP_RDD_Katz_dEdx_kernel().
float SGP_RDD_Katz_dEdx_J_m (float * alpha, float * r_min_m, float * r_max_m, float * Katz_dEdx_coeff_J_m)
Definition at line 75 of file SGP_RDD.c.
float SGP_RDD_Katz_dEdx_kernel (float * x, float * alpha) [inline]
Definition at line 54 of file SGP_RDD.c.
void SGP_RDD_Katz_dEdx_kernelS (int * n, float * x, float * alpha, float * f)
Definition at line 58 of file SGP_RDD.c.
References SGP_RDD_Katz_dEdx_kernel().
float SGP_RDD_Katz_ext_Gy (float * r_m, float * a0_m, float * alpha, float * r_min_m, float * r_max_m, float * Katz_point_coeff_Gy) [inline]
Definition at line 186 of file SGP_RDD.c.
References SGP_RDD_Katz_ext_integrand_Gy().
void SGP_RDD_Katz_ext_GyS (int * n, float * r_m, float * a0_m, float * alpha, float * r_min_m, float * r_max_m, float * Katz_point_coeff_Gy, float * D_Gy)
Definition at line 214 of file SGP_RDD.c.
References SGP_RDD_Katz_ext_Gy().
double SGP_RDD_Katz_ext_integrand_Gy (double t_m, void * params)
Definition at line 174 of file SGP_RDD.c.
References SGP_RDD_Katz_ext_kernel_Gy().
float SGP_RDD_Katz_ext_kernel_Gy (float * t_m, float * r_m, float * a0_m, float * alpha, float * r_min_m, float * r_max_m, float * Katz_point_coeff_Gy) [inline]
Definition at line 144 of file SGP_RDD.c.
References geometryFunctionPhi(), and SGP_RDD_Katz_point_Gy().
void SGP_RDD_Katz_ext_kernel_GyS (int * n, float * t_m, float * r_m, float * a0_m, float * alpha, float * r_min_m, float * r_max_m, float * Katz_point_coeff_Gy, float * D_Gy)
Definition at line 162 of file SGP_RDD.c.
References SGP_RDD_Katz_ext_kernel_Gy().
float SGP_RDD_Katz_point_coeff_Gy (float * C_J_m, float * Z_eff, float * beta, float * alpha, float * density_kg_m3, float * r_max_m) [inline]
Definition at line 38 of file SGP_RDD.c.
float SGP_RDD_Katz_point_Gy (float * r_m, float * alpha, float * r_max_m, float * Katz_point_coeff_Gy) [inline]
Definition at line 42 of file SGP_RDD.c.
References SGP_RDD_Katz_point_kernel().
void SGP_RDD_Katz_point_GyS (int * n, float * r_m, float * alpha, float * r_max_m, float * Katz_point_coeff_Gy, float * D)
Definition at line 47 of file SGP_RDD.c.
References SGP_RDD_Katz_point_Gy().
float SGP_RDD_Katz_point_kernel (float * x, float * alpha) [inline]
Definition at line 27 of file SGP_RDD.c.
void SGP_RDD_Katz_point_kernelS (int * n, float * x, float * alpha, float * f)
Definition at line 31 of file SGP_RDD.c.
References SGP_RDD_Katz_point_kernel().
float SGP_RDD_Katz_site_Gy (float * r_m, float * alpha, float * r_min_m, float * r_max_m, float * LET_J_m, float * density_kg_m3, float * Katz_dEdx_J_m, float * Katz_point_coeff_Gy) [inline]
Definition at line 88 of file SGP_RDD.c.
References SGP_RDD_Katz_point_Gy().
void SGP_RDD_Katz_site_GyS (int * n, float * r_m, float * alpha, float * r_min_m, float * r_max_m, float * LET_J_m, float * density_kg_m3, float * Katz_dEdx_J_m, float * Katz_point_coeff_Gy, float * D_Gy)
Definition at line 97 of file SGP_RDD.c.
References SGP_RDD_Katz_site_Gy().