libSGP: SGP_SuccessiveConvolutions.h File Reference
SGP_SuccessiveConvolutions.h File Reference
#include <stdbool.h>
Functions
void SGP_SC_get_f1_array_size (long *n, float *E_MeV_u, long *particle_no, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, long *N2, long *n_bins_f1, float *f1_parameters)
void SGP_SC_get_f1 (long *n, float *E_MeV_u, long *particle_no, float *fluence_cm2, long *material_no, long *rdd_model, float *rdd_parameter, long *er_model, float *er_parameter, long *N2, long *n_bins_f1, float *f1_parameters, float *norm_fluence, float *dose_contribution_Gy, float *f_parameters, float *f1_d_Gy, float *f1_dd_Gy, float *f1)
void SGP_SC_get_f_array_size (float *u, float *fluence_factor, long *N2, long *n_bins_f1, float *f1_d_Gy, float *f1_dd_Gy, float *f1, long *n_bins_f, float *u_start, long *n_convolutions)
void SGP_SC_get_f_start (float *u_start, long *n_bins_f1, long *N2, float *f1_d_Gy, float *f1_dd_Gy, float *f1, long *n_bins_f, float *f_d_Gy, float *f_dd_Gy, float *f_start)
void SGP_SuccessiveConvolutions (float *u, long *n_bins_f, long *N2, long *n_bins_f_used, float *f_d_Gy, float *f_dd_Gy, float *f, float *f0, float *fdd, float *dfdd, float *d, bool *write_output, bool *shrink_tails, float *shrink_tails_under, bool *adjust_N2)
Function Documentation
void SGP_SC_get_f1 (long * n, float * E_MeV_u, long * particle_no, float * fluence_cm2, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, long * N2, long * n_bins_f1, float * f1_parameters, float * norm_fluence, float * dose_contribution_Gy, float * f_parameters, float * f1_d_Gy, float * f1_dd_Gy, float * f1)
Definition at line 112 of file SGP_SuccessiveConvolutions.c.
References FMAX, FMIN, LMAX, locate(), MeV_g_to_J_kg, and SGP_r_RDD_m().
void SGP_SC_get_f1_array_size (long * n, float * E_MeV_u, long * particle_no, long * material_no, long * rdd_model, float * rdd_parameter, long * er_model, float * er_parameter, long * N2, long * n_bins_f1, float * f1_parameters)
Definition at line 26 of file SGP_SuccessiveConvolutions.c.
References FMAX, FMIN, and SGP_RDD_f1_parameters().
void SGP_SC_get_f_array_size (float * u, float * fluence_factor, long * N2, long * n_bins_f1, float * f1_d_Gy, float * f1_dd_Gy, float * f1, long * n_bins_f, float * u_start, long * n_convolutions)
Definition at line 404 of file SGP_SuccessiveConvolutions.c.
References MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT.
void SGP_SC_get_f_start (float * u_start, long * n_bins_f1, long * N2, float * f1_d_Gy, float * f1_dd_Gy, float * f1, long * n_bins_f, float * f_d_Gy, float * f_dd_Gy, float * f_start)
Definition at line 476 of file SGP_SuccessiveConvolutions.c.
void SGP_SuccessiveConvolutions (float * u, long * n_bins_f, long * N2, long * n_bins_f_used, float * f_d_Gy, float * f_dd_Gy, float * f, float * f0, float * fdd, float * dfdd, float * d, bool * write_output, bool * shrink_tails, float * shrink_tails_under, bool * adjust_N2)
Definition at line 1047 of file SGP_SuccessiveConvolutions.c.
References aKList::A, aKList::adjust_N2, aKList::array_size, aKList::BI, aKList::CM1, aKList::CM2, aKList::CM3, aKList::CM4, aKList::CN, aKList::D1, aKList::D2, aKList::D3, aKList::D4, aKList::DE, aKList::DI, aKList::E, aKList::E0, aKList::F, aKList::F0, aKList::FINAL, aKList::H, aKList::H0, aKList::LEF, aKList::LEH, MEAN_HIT_NUMBER_LINEAR_APPROX_LIMIT, aKList::MIE, aKList::MIF, aKList::MIH, aKList::N1, aKList::N2, aKList::output_file, SGP_SC_FOLD(), SGP_SC_NORMAL(), SGP_SC_OUTPUT(), SGP_SC_SHRINK(), aKList::shrink_tails, aKList::shrink_tails_under, aKList::U, aKList::write_output, and aKList::X.