name: Linux Build & Test

on:
  push:
    branches: [ master ]
    tags: ['v*']
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build_and_test_linux:
    name: Linux Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system packages
        run: sudo apt-get install -y --no-install-recommends libgsl-dev

      - name: Build & Install libamtrack (Linux)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel
          cmake --install . --prefix "${{ runner.temp }}/usr"
      
      - name: Run Linux Tests
        run: |
          export PATH="${{ runner.temp }}/usr/bin:$PATH"
          export LD_LIBRARY_PATH="${{ runner.temp }}/usr/lib:$LD_LIBRARY_PATH"
          amtrack_test
          amtrack_demo

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libamtrack-linux
          path: "${{ runner.temp }}/usr/"
          if-no-files-found: error
          retention-days: 5
